### PR TITLE
feat/styling

### PR DESCRIPTION
**Pull request by nicedexter**
- Styling components
- Refactor server rendering to client for parametrized pages

### CODE REVIEW

**Comment by greut** [comment]
Sorry, I cannot review this.

**Comment by nicedexter** [comment]
Why not ?

**Comment by greut** [comment]
> Why not ?

This is how I do JavaScript. https://yoan.dosimple.ch/blockdude/game.js

**Comment by nicedexter** [comment]
Cool ! XMLHttpRequest style 
The web-ui weight 30 Mb, so I guess we could use that kind of sobriety ^^

**Pull request merged**
